#!/bin/bash

MYSQL_DB_NAME=db-wordpress
MYSQL_USER=aben-cha
MYSQL_PASSWORD=123456789
MYSQL_ROOT_PASSWORD=123456789


# mysql -u root -p${MYSQL_ROOT_PASSWORD} <<EOF
cat << EOF > init.sql
CREATE DATABASE IF NOT EXISTS \`${MYSQL_DB_NAME}\`;
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${MYSQL_DB_NAME}\`.* TO '${MYSQL_USER}'@'%';
FLUSH PRIVILEGES;
EOF
