services:
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    env_file:
      - .env
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - wp-network
    volumes:
      - db:/var/lib/mysql
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress-php
    image: wordpress:6.7.1-php8.3-fpm
    restart: always
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    ports:
      - "8080:80"
    networks:
      - wp-network
    volumes:
      - wordpress:/var/www/html

networks:
  wp-network:
    driver: bridge


volumes:
  db:
  wordpress:
