server {
    listen 80;
    server_name localhost;

        # Set proper Content-Type
    add_header Content-Type "text/html; charset=UTF-8";
    
    # Add security headers
    add_header Referrer-Policy "strict-origin-when-cross-origin";
    
    # Enable gzip compression since Accept-Encoding shows "gzip, deflate"
    gzip on;
    gzip_types text/html application/xhtml+xml application/xml application/javascript text/css;

    
    root /var/www/html;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress:9000; # Connect to the WordPress container's PHP-FPM service
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.ht {
        deny all;
    }
}