services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - inception
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: requirements/wordpress/
    env_file:
      - .env
    # volumes:
      # - ./wordpress:/var/www/wordpress
    networks:
      - inception
#   nginx:
#     container_name: nginx
#     image: nginx:latest
#     depends_on:
#       - wordpress
#     ports:
#       - "8080:80"
#     networks:
#       - inception
#     volumes:
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf;
#       - ./wordpress:/var/www/wordpress
networks:
  inception:
    driver: bridge
    