services:
  db:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: shop
      MYSQL_USER: aben-cha
      MYSQL_PASSWORD: aben-cha
      MYSQL_ROOT_PASSWORD: aben-cha123
    volumes:
      - db_data:/var/lib/mysql
  wordpress:
    depends_on:
      - db
    container_name: wordpress
    image: wordpress:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: shop
      WORDPRESS_DB_USER: aben-cha
      WORDPRESS_DB_PASSWORD: aben-cha
    volumes:
      - wordpress:/var/www/html

volumes:
  wordpress:
  db_data: