services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: requirements/wordpress/
    env_file:
      - .env
    expose:
      - 9000
    volumes:
      - wordpress_data:/var/www/html 
    networks:
      - inception
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: requirements/nginx/
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html 
      # - ./default.conf:/etc/nginx/conf.d/default.conf;


networks:
  inception:
    driver: bridge

volumes:
  wordpress_data:
  db_data:
    